// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV830OtVTzIIDkftEkNfkyRTuULB002yc',
    appId: '1:515483338000:web:e1392d7afca641699fd195',
    messagingSenderId: '515483338000',
    projectId: 'notes-b6f6d',
    authDomain: 'notes-b6f6d.firebaseapp.com',
    storageBucket: 'notes-b6f6d.appspot.com',
    measurementId: 'G-4VTVNPE05Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkyZSzpN-8nSa6YFGqLFwQIqsUZ-jUuJM',
    appId: '1:515483338000:android:837dcd33f6f60e699fd195',
    messagingSenderId: '515483338000',
    projectId: 'notes-b6f6d',
    storageBucket: 'notes-b6f6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfD7jTsCWFzUVogI-3hzJPuUPEOvHkQWM',
    appId: '1:515483338000:ios:f981859c5c49bfc49fd195',
    messagingSenderId: '515483338000',
    projectId: 'notes-b6f6d',
    storageBucket: 'notes-b6f6d.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfD7jTsCWFzUVogI-3hzJPuUPEOvHkQWM',
    appId: '1:515483338000:ios:f981859c5c49bfc49fd195',
    messagingSenderId: '515483338000',
    projectId: 'notes-b6f6d',
    storageBucket: 'notes-b6f6d.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV830OtVTzIIDkftEkNfkyRTuULB002yc',
    appId: '1:515483338000:web:1ed42fc82166f8179fd195',
    messagingSenderId: '515483338000',
    projectId: 'notes-b6f6d',
    authDomain: 'notes-b6f6d.firebaseapp.com',
    storageBucket: 'notes-b6f6d.appspot.com',
    measurementId: 'G-GZBZ4DWYRD',
  );

}